name = "timelog2"
pages_build_output_dir = ".next"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "npm run build"

[vars]
apiKey = "AIzaSyCJyfw-oA4YtdLrVvFdrhFFjkXEUj99Ifo"
projectId = "studio-8099195455-af266"
authDomain = "studio-8099195455-af266.firebaseapp.com"
databaseURL = "https://studio-8099195455-af266.firebaseio.com"
